apiVersion: scaler.buaa.io/v1
kind: Scaler
metadata:
  labels:
    app.kubernetes.io/name: scaler
    app.kubernetes.io/instance: scaler-sample
    app.kubernetes.io/part-of: scaler
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: scaler
  name: scaler-sample
spec:
  application:
    name: first-scaler
    nameSpace: mytest
    image: nginx
    replica: 2
    ports:
      - name: my-port
        port: 8080
